# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: b8e0237eef28c1257d75970748275d954ed70a4ee8adbc8fda9b7d6e28af21f485b54e7e6358f9b43aef24e08b70358aac4a825de544fd6189a38a173bcce154

test:
  secret_key_base: 04fc0cccd1efe99f24f3981e7733427c76501231230c05cb57bf6aed5d9b40358ab40b4f10e9cb17958ef61ce2a7afb5d7f927cbca6e4adb31472ce1da3208f9

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
